### ISSUE TITLE
grilo-plugin - readme - install statement lacks grilo version env variable

### ISSUE THREAD

**Issue by prahal** [swenner/totem-plugin-arte#1]
README of grilo-plugin branch tell to:
make GRILO_VERSION=3
sudo make install

to get the plugin to install in the grilo 0.3 directory I had to set the environment variable for both (else it ended up in the grilo 0.2 directory) :
make GRILO_VERSION=3
sudo make GRILO_VERSION=3 install

Tested against totem 3.20.1-3 ,  run well. Thanks !

**Comment by swenner** [comment]
You are right. Thank you for the report. I fixed it.
